### ISSUE TITLE
How to catch ECONNREFUSED?

### ISSUE THREAD

**Issue by goloroden** [browserify/http-browserify#51]
In Node.js, when using the `request` function of the `http` module, you can subscribe to the `error` events of the returned object, such as:

```
var http = require('http');

var req = http.request('aaa.bbb.ccc.ddd', function (res) {
  console.log(res.statusCode);
});

req.on('error', function (err) {
  console.log('###');
});

req.end();
```

When I run this with a non-existent IP on Node.js, everything is fine, and the result is `###` printed to the console.

When I run this using `http-browserify` in Chrome, I get an uncaught exception. Am I doing something wrong?

**Comment by JamesMessinger** [comment]
I'm having the same issue.   Any resolution to this?

**Comment by goloroden** [comment]
Unfortunately, I don't have one :-(

**Comment by langri-sha** [comment]
I believe you will have to listen to the window for these uncaught network errors and decide what to do with them.
